title: Todohack
description: >
  Bienvenidos a la Ciberseguridad y el Hacking Ético
permalink: ':title/'
baseurl: ""
url: "https://todohack.github.io"

# Author Settings
author: TodoHack
author-img: todohack.jpg
about-author: Soy un Especialista en Ciberseguridad, experimentado soportista en sistemas, con mucha pasión por el hacking ético y con hambre de conocimiento
social-github: todohack
social-linkedin: jcz-it/
social-email: hackerjucazu@gmail.com

# Disqus
disqus:
    shortname: "todohack"
    
defaults:

type: "posts"
layout: "post"
comments: true
  
# Tracker
analytics: Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"
